/**
 * GENERATED FILE — do not edit by hand.
 *
 * The verified YAK food catalog: every predefined food, its nutrition
 * source, and its explicitly defined servings. Nutrition values are copied
 * verbatim from the cited record (USDA FoodData Central fdcId, or an
 * official manufacturer label) — see `source` on each entry. The
 * raw source records used for verification are kept under server/audit/.
 *
 * State ("as consumed"): cooked for foods normally eaten cooked (meat,
 * fish, rice, legumes, dishes), raw for fruit/raw vegetables, as-sold for
 * packaged/ready products, dry for oats (weighed dry).
 */
import type { CatalogFood } from './foodCatalog';

export const FOOD_CATALOG_DATA: CatalogFood[] = [
  {
    id: "yumurta",
    name: "Yumurta",
    aliases: ["egg", "whole egg", "chicken egg", "haslanmis yumurta"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 155, protein: 12.58, carbs: 1.12, fat: 10.61 },
    source: { kind: "usda-fdc", reference: "FDC #173424", description: "Egg, whole, cooked, hard-boiled", url: "https://fdc.nal.usda.gov/food-details/173424/nutrients" },
    adet: { grams: 50, label: "1 büyük yumurta", basis: "USDA FDC #173424 ölçüsü: 1 large = 50 g" },
  },
  {
    id: "tavuk",
    name: "Tavuk",
    aliases: ["chicken", "chicken meat", "tavuk eti"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 190, protein: 28.93, carbs: 0, fat: 7.41 },
    source: { kind: "usda-fdc", reference: "FDC #171054", description: "Chicken, broilers or fryers, meat only, cooked, roasted", url: "https://fdc.nal.usda.gov/food-details/171054/nutrients" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "tavuk-gogsu",
    name: "Tavuk göğsü",
    aliases: ["tavuk gogsusu", "chicken breast", "tavuk fileto"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 165, protein: 31.02, carbs: 0, fat: 3.57 },
    source: { kind: "usda-fdc", reference: "FDC #171477", description: "Chicken, broilers or fryers, breast, meat only, cooked, roasted", url: "https://fdc.nal.usda.gov/food-details/171477/nutrients" },
    adet: { grams: 86, label: "1 yarım göğüs (fileto)", basis: "USDA FDC #171477 ölçüsü: 0.5 breast, bone and skin removed = 86 g" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "pirinc",
    name: "Pirinç",
    aliases: ["rice", "white rice", "cooked rice", "pirinc pilavi sade", "haslanmis pirinc"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 130, protein: 2.69, carbs: 28.17, fat: 0.28 },
    source: { kind: "usda-fdc", reference: "FDC #168878", description: "Rice, white, long-grain, regular, enriched, cooked", url: "https://fdc.nal.usda.gov/food-details/168878/nutrients" },
    porsiyon: { grams: 158, label: "1 su bardağı (pişmiş)", basis: "USDA FDC #168878 ölçüsü: 1 cup = 158 g" },
  },
  {
    id: "muz",
    name: "Muz",
    aliases: ["banana", "bananas"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 89, protein: 1.09, carbs: 22.84, fat: 0.33 },
    source: { kind: "usda-fdc", reference: "FDC #173944", description: "Bananas, raw", url: "https://fdc.nal.usda.gov/food-details/173944/nutrients" },
    adet: { grams: 118, label: "1 orta boy muz", basis: "USDA FDC #173944 ölçüsü: 1 medium = 118 g" },
  },
  {
    id: "yogurt",
    name: "Yoğurt",
    aliases: ["yoghurt", "plain yogurt", "sade yogurt", "tam yagli yogurt"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 78, protein: 3.82, carbs: 5.57, fat: 4.48 },
    source: { kind: "usda-fdc", reference: "FDC #2705418", description: "Yogurt, whole milk, plain", url: "https://fdc.nal.usda.gov/food-details/2705418/nutrients" },
    porsiyon: { grams: 200, label: "1 kase", basis: "YAK tanımı: 1 kase / su bardağı yoğurt = 200 g" },
  },
  {
    id: "ton-baligi",
    name: "Ton balığı",
    aliases: ["tuna", "ton baligi konserve", "tuna in oil", "canned tuna"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 198, protein: 29.13, carbs: 0, fat: 8.21 },
    source: { kind: "usda-fdc", reference: "FDC #173708", description: "Fish, tuna, light, canned in oil, drained solids", url: "https://fdc.nal.usda.gov/food-details/173708/nutrients" },
    porsiyon: { grams: 100, label: "1 porsiyon", basis: "YAK tanımı: 100 g" },
  },
  {
    id: "tatli-patates",
    name: "Tatlı patates",
    aliases: ["sweet potato", "sweet potatoes"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 76, protein: 1.37, carbs: 17.72, fat: 0.14 },
    source: { kind: "usda-fdc", reference: "FDC #168484", description: "Sweet potato, cooked, boiled, without skin", url: "https://fdc.nal.usda.gov/food-details/168484/nutrients" },
    adet: { grams: 151, label: "1 orta boy tatlı patates", basis: "USDA FDC #168484 ölçüsü: 1 medium = 151 g" },
  },
  {
    id: "elma",
    name: "Elma",
    aliases: ["apple", "apples"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 52, protein: 0.26, carbs: 13.81, fat: 0.17 },
    source: { kind: "usda-fdc", reference: "FDC #171688", description: "Apples, raw, with skin", url: "https://fdc.nal.usda.gov/food-details/171688/nutrients" },
    adet: { grams: 182, label: "1 orta boy elma", basis: "USDA FDC #171688 ölçüsü: 1 medium (3\" dia) = 182 g" },
  },
  {
    id: "domates",
    name: "Domates",
    aliases: ["tomato", "tomatoes"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 18, protein: 0.88, carbs: 3.89, fat: 0.2 },
    source: { kind: "usda-fdc", reference: "FDC #170457", description: "Tomatoes, red, ripe, raw, year round average", url: "https://fdc.nal.usda.gov/food-details/170457/nutrients" },
    adet: { grams: 123, label: "1 orta boy domates", basis: "USDA FDC #170457 ölçüsü: 1 medium whole = 123 g" },
  },
  {
    id: "salatalik",
    name: "Salatalık",
    aliases: ["cucumber", "hiyar"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 15, protein: 0.65, carbs: 3.63, fat: 0.11 },
    source: { kind: "usda-fdc", reference: "FDC #168409", description: "Cucumber, with peel, raw", url: "https://fdc.nal.usda.gov/food-details/168409/nutrients" },
    adet: { grams: 120, label: "1 orta boy salatalık", basis: "YAK tanımı: Türkiye'deki orta boy salatalık ≈120 g (USDA'nın tek ölçüsü 301 g'lık ABD salatalığıdır)" },
  },
  {
    id: "hindi",
    name: "Hindi",
    aliases: ["turkey", "turkey meat", "hindi eti"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 159, protein: 29.06, carbs: 0, fat: 3.84 },
    source: { kind: "usda-fdc", reference: "FDC #171481", description: "Turkey, whole, meat only, cooked, roasted", url: "https://fdc.nal.usda.gov/food-details/171481/nutrients" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "hindi-gogsu",
    name: "Hindi göğsü",
    aliases: ["hindi gogsusu", "turkey breast"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 147, protein: 30.13, carbs: 0, fat: 2.08 },
    source: { kind: "usda-fdc", reference: "FDC #171496", description: "Turkey, whole, breast, meat only, cooked, roasted", url: "https://fdc.nal.usda.gov/food-details/171496/nutrients" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "yaban-mersini",
    name: "Yaban mersini",
    aliases: ["blueberry", "blueberries"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 57, protein: 0.74, carbs: 14.49, fat: 0.33 },
    source: { kind: "usda-fdc", reference: "FDC #171711", description: "Blueberries, raw", url: "https://fdc.nal.usda.gov/food-details/171711/nutrients" },
    porsiyon: { grams: 148, label: "1 kase", basis: "USDA FDC #171711 ölçüsü: 1 cup = 148 g" },
  },
  {
    id: "avokado",
    name: "Avokado",
    aliases: ["avocado", "avocados"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 160, protein: 2, carbs: 8.53, fat: 14.66 },
    source: { kind: "usda-fdc", reference: "FDC #171705", description: "Avocados, raw, all commercial varieties", url: "https://fdc.nal.usda.gov/food-details/171705/nutrients" },
    adet: { grams: 201, label: "1 avokado", basis: "USDA FDC #171705 ölçüsü: 1 avocado = 201 g" },
  },
  {
    id: "yulaf",
    name: "Yulaf",
    aliases: ["oats", "oat", "oatmeal", "rolled oats", "yulaf ezmesi"],
    state: "dry",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 379, protein: 13.15, carbs: 67.7, fat: 6.52 },
    source: { kind: "usda-fdc", reference: "FDC #173904", description: "Cereals, oats, regular and quick, not fortified, dry", url: "https://fdc.nal.usda.gov/food-details/173904/nutrients" },
    porsiyon: { grams: 40, label: "1 porsiyon (kuru, ~4 yemek kaşığı)", basis: "YAK tanımı: 40 g kuru yulaf" },
  },
  {
    id: "badem",
    name: "Badem",
    aliases: ["almond", "almonds"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 579, protein: 21.15, carbs: 21.55, fat: 49.93 },
    source: { kind: "usda-fdc", reference: "FDC #170567", description: "Nuts, almonds", url: "https://fdc.nal.usda.gov/food-details/170567/nutrients" },
    porsiyon: { grams: 28.35, label: "1 avuç (~23 badem)", basis: "USDA FDC #170567 ölçüsü: 1 oz (23 whole kernels) = 28.35 g" },
  },
  {
    id: "kaju",
    name: "Kaju",
    aliases: ["cashew", "cashews", "cashew nuts"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 574, protein: 15.31, carbs: 32.69, fat: 46.35 },
    source: { kind: "usda-fdc", reference: "FDC #170571", description: "Nuts, cashew nuts, dry roasted, without salt added", url: "https://fdc.nal.usda.gov/food-details/170571/nutrients" },
    porsiyon: { grams: 28.35, label: "1 avuç", basis: "USDA FDC #170571 ölçüsü: 1 oz = 28.35 g" },
  },
  {
    id: "somon",
    name: "Somon",
    aliases: ["salmon", "atlantic salmon"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 206, protein: 22.1, carbs: 0, fat: 12.35 },
    source: { kind: "usda-fdc", reference: "FDC #175168", description: "Fish, salmon, Atlantic, farmed, cooked, dry heat", url: "https://fdc.nal.usda.gov/food-details/175168/nutrients" },
    adet: { grams: 178, label: "1 fileto", basis: "USDA FDC #175168 ölçüsü: 0.5 fillet = 178 g" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "dana-eti",
    name: "Dana eti",
    aliases: ["beef", "beef meat", "kusbasi", "kusbasi dana"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 233, protein: 28.17, carbs: 0, fat: 12.53 },
    source: { kind: "usda-fdc", reference: "FDC #170206", description: "Beef, composite of trimmed retail cuts, separable lean and fat, trimmed to 0\" fat, choice, cooked", url: "https://fdc.nal.usda.gov/food-details/170206/nutrients" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "doner",
    name: "Döner",
    aliases: ["doner", "döner", "et doner", "doner et", "dana doner", "beef doner", "yaprak doner", "porsiyon doner", "doner kebap", "doner kebab"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 361, protein: 17.9, carbs: 3.8, fat: 30.5 },
    source: { kind: "manufacturer-label", reference: "Maret ürün etiketi (Migros ürün sayfası)", description: "Maret Pişmiş Dondurulmuş Dana Döner (100 g)", url: "https://www.migros.com.tr/maret-pismis-dondurulmus-dana-doner-500-g-p-10980d1" },
  },
  { id: "doner-ekmek", name: "Ekmek arası döner", aliases: ["ekmek arasi doner", "doner ekmek arasi", "yarim ekmek doner", "durum doner", "doner durum", "gyro", "gyro sandwich"], state: "as-sold", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: ekmek arası / dürüm döner için doğrulanmış besin değeri yok (ekmek, sos ve sebze miktarı değişken)." },
  { id: "tavuk-doner", name: "Tavuk döner", aliases: ["chicken doner", "chicken gyro", "chicken shawarma", "doner tavuk"], state: "cooked", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: USDA'da pişmiş tavuk döner karşılığı yok." },
  { id: "adana-kebap", name: "Adana Kebap", aliases: ["adana kebab", "adana"], state: "cooked", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: USDA'da karşılığı yok." },
  {
    id: "hamburger",
    name: "Hamburger",
    aliases: ["burger", "beef burger"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 288, protein: 17.5, carbs: 20.7, fat: 14.4 },
    source: { kind: "usda-fdc", reference: "FDC #2706932", description: "Hamburger, on white bun, 1 medium patty", url: "https://fdc.nal.usda.gov/food-details/2706932/nutrients" },
    adet: { grams: 145, label: "1 hamburger", basis: "USDA FDC #2706932 ölçüsü: 1 hamburger = 145 g" },
  },
  {
    id: "patates-kizartmasi",
    name: "Patates kızartması",
    aliases: ["french fries", "fries", "french fried potatoes"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 312, protein: 3.43, carbs: 41.44, fat: 14.73 },
    source: { kind: "usda-fdc", reference: "FDC #170698", description: "Fast foods, potato, french fried in vegetable oil", url: "https://fdc.nal.usda.gov/food-details/170698/nutrients" },
    porsiyon: { grams: 117, label: "1 orta porsiyon", basis: "USDA FDC #170698 ölçüsü: 1 serving medium = 117 g" },
  },
  { id: "iskender", name: "İskender", aliases: ["iskender kebap", "iskender kebab"], state: "cooked", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: USDA'da karşılığı yok." },
  {
    id: "levrek",
    name: "Levrek",
    aliases: ["sea bass"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 124, protein: 23.63, carbs: 0, fat: 2.56 },
    source: { kind: "usda-fdc", reference: "FDC #173694", description: "Fish, sea bass, mixed species, cooked, dry heat", url: "https://fdc.nal.usda.gov/food-details/173694/nutrients" },
    adet: { grams: 101, label: "1 fileto", basis: "USDA FDC #173694 ölçüsü: 1 fillet = 101 g" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  { id: "cipura", name: "Çipura", aliases: ["sea bream", "gilthead seabream"], state: "cooked", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: USDA'da pişmiş çipura yok." },
  {
    id: "sardalya",
    name: "Sardalya",
    aliases: ["sardine", "sardines", "sardalya konserve"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 208, protein: 24.62, carbs: 0, fat: 11.45 },
    source: { kind: "usda-fdc", reference: "FDC #175139", description: "Fish, sardine, Atlantic, canned in oil, drained solids with bone", url: "https://fdc.nal.usda.gov/food-details/175139/nutrients" },
    porsiyon: { grams: 100, label: "1 porsiyon", basis: "YAK tanımı: 100 g" },
  },
  { id: "palamut", name: "Palamut", aliases: ["bonito", "atlantic bonito"], state: "cooked", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: USDA'da pişmiş palamut yok." },
  { id: "lahmacun", name: "Lahmacun", aliases: ["turkish pizza"], state: "cooked", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: USDA'da karşılığı yok." },
  {
    id: "ceviz",
    name: "Ceviz",
    aliases: ["walnut", "walnuts"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 654, protein: 15.23, carbs: 13.71, fat: 65.21 },
    source: { kind: "usda-fdc", reference: "FDC #170187", description: "Nuts, walnuts, english", url: "https://fdc.nal.usda.gov/food-details/170187/nutrients" },
    porsiyon: { grams: 28.35, label: "1 avuç (~14 yarım ceviz)", basis: "USDA FDC #170187 ölçüsü: 1 oz (14 halves) = 28.35 g" },
  },
  {
    id: "portakal",
    name: "Portakal",
    aliases: ["orange", "oranges"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 47, protein: 0.94, carbs: 11.75, fat: 0.12 },
    source: { kind: "usda-fdc", reference: "FDC #169097", description: "Oranges, raw, all commercial varieties", url: "https://fdc.nal.usda.gov/food-details/169097/nutrients" },
    adet: { grams: 131, label: "1 orta boy portakal", basis: "USDA FDC #169097 ölçüsü: 1 fruit (2-5/8\" dia) = 131 g" },
  },
  {
    id: "mercimek",
    name: "Mercimek",
    aliases: ["lentil", "lentils", "cooked lentils", "haslanmis mercimek"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 116, protein: 9.02, carbs: 20.13, fat: 0.38 },
    source: { kind: "usda-fdc", reference: "FDC #172421", description: "Lentils, mature seeds, cooked, boiled, without salt", url: "https://fdc.nal.usda.gov/food-details/172421/nutrients" },
    porsiyon: { grams: 198, label: "1 su bardağı (pişmiş)", basis: "USDA FDC #172421 ölçüsü: 1 cup = 198 g" },
  },
  {
    id: "mercimek-corbasi",
    name: "Mercimek çorbası",
    aliases: ["lentil soup"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 60, protein: 3.82, carbs: 10.2, fat: 0.69 },
    source: { kind: "usda-fdc", reference: "FDC #2707462", description: "Soup, lentil", url: "https://fdc.nal.usda.gov/food-details/2707462/nutrients" },
    porsiyon: { grams: 255, label: "1 kase", basis: "USDA FDC #2707462 ölçüsü: 1 cup = 255 g" },
  },
  {
    id: "sut",
    name: "Süt",
    aliases: ["milk", "whole milk", "tam yagli sut", "inek sutu"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 61, protein: 3.15, carbs: 4.8, fat: 3.25 },
    source: { kind: "usda-fdc", reference: "FDC #171265", description: "Milk, whole, 3.25% milkfat, with added vitamin D", url: "https://fdc.nal.usda.gov/food-details/171265/nutrients" },
    density: { gramsPerMl: 1.031, basis: "USDA FDC #171265 ölçüsü: 1 su bardağı (236,6 ml) süt = 244 g" },
    porsiyon: { ml: 200, label: "1 su bardağı", basis: "YAK tanımı: 1 su bardağı = 200 ml" },
  },
  {
    id: "ayran",
    name: "Ayran",
    aliases: ["yogurt drink", "drinkable yogurt"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100ml", calories: 32, protein: 2, carbs: 2, fat: 1.8 },
    source: { kind: "manufacturer-label", reference: "Sütaş ürün etiketi", description: "Sütaş Ayran (100 ml)", url: "https://www.sutas.com/sutas-ayran-1-l" },
    density: { gramsPerMl: 1.031, basis: "USDA FDC #171265 ölçüsü: 1 su bardağı (236,6 ml) süt = 244 g" },
    porsiyon: { ml: 200, label: "1 su bardağı", basis: "YAK tanımı: 1 su bardağı = 200 ml" },
  },
  {
    id: "pizza",
    name: "Pizza",
    aliases: ["cheese pizza", "peynirli pizza"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 266, protein: 11.4, carbs: 33.3, fat: 9.69 },
    source: { kind: "usda-fdc", reference: "FDC #2708616", description: "Pizza, cheese, from restaurant or fast food, medium crust", url: "https://fdc.nal.usda.gov/food-details/2708616/nutrients" },
    adet: { grams: 691, label: "1 orta boy pizza (28-30 cm)", basis: "USDA FDC #2708616 ölçüsü: 1 medium pizza (11-12\" diameter) = 691 g" },
    porsiyon: { grams: 86, label: "1 dilim", basis: "USDA FDC #2708616 ölçüsü: 1 piece, medium pizza = 86 g" },
  },
  {
    id: "kefir",
    name: "Kefir",
    aliases: ["plain kefir", "sade kefir"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100ml", calories: 45, protein: 2.8, carbs: 4.7, fat: 1.7 },
    source: { kind: "manufacturer-label", reference: "Pınar ürün etiketi", description: "Pınar Kefir, sade (100 ml)", url: "https://www.pinar.com.tr/urunler/detay-sut/Kefir/3642/0/0" },
    density: { gramsPerMl: 1.031, basis: "USDA FDC #2705394 ölçüsü: 1 cup kefir = 244 g" },
    porsiyon: { ml: 200, label: "1 su bardağı", basis: "YAK tanımı: 1 su bardağı = 200 ml" },
  },
  {
    id: "cola-zero",
    name: "Cola Zero",
    aliases: ["coca cola zero", "coca-cola zero", "coke zero", "cola zero sugar", "coca cola zero sugar", "kola zero", "zero cola"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100ml", calories: 0.2, protein: 0, carbs: 0, fat: 0 },
    source: { kind: "manufacturer-label", reference: "Coca-Cola Türkiye ürün etiketi", description: "Coca-Cola Zero Sugar (100 ml)", url: "https://www.coca-cola.com/tr/tr/brands/coca-cola" },
    density: { gramsPerMl: 1.001, basis: "USDA FDC #174850 ölçüsü: diyet kola 1 fl oz (29,57 ml) = 29,6 g" },
    adet: { ml: 330, label: "1 kutu (330 ml)", basis: "Standart Türkiye kutu hacmi 330 ml" },
    porsiyon: { ml: 200, label: "1 su bardağı", basis: "YAK tanımı: 1 su bardağı = 200 ml" },
  },
  {
    id: "cola",
    name: "Cola",
    aliases: ["kola", "coca cola", "coca-cola", "coke", "regular cola"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100ml", calories: 42, protein: 0, carbs: 10.6, fat: 0 },
    source: { kind: "manufacturer-label", reference: "Coca-Cola Türkiye ürün etiketi", description: "Coca-Cola Original Taste (100 ml)", url: "https://www.coca-cola.com/tr/tr/brands/coca-cola" },
    density: { gramsPerMl: 1.038, basis: "USDA FDC #174852 ölçüsü: kola 1 fl oz (29,57 ml) = 30,7 g" },
    adet: { ml: 330, label: "1 kutu (330 ml)", basis: "Standart Türkiye kutu hacmi 330 ml" },
    porsiyon: { ml: 200, label: "1 su bardağı", basis: "YAK tanımı: 1 su bardağı = 200 ml" },
  },
  {
    id: "yumurta-aki",
    name: "Yumurta akı",
    aliases: ["egg white", "egg whites", "yumurta beyazi"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 52, protein: 10.9, carbs: 0.73, fat: 0.17 },
    source: { kind: "usda-fdc", reference: "FDC #172183", description: "Egg, white, raw, fresh", url: "https://fdc.nal.usda.gov/food-details/172183/nutrients" },
    adet: { grams: 33, label: "1 yumurtanın akı", basis: "USDA FDC #172183 ölçüsü: 1 large egg white = 33 g" },
  },
  {
    id: "tavuk-but",
    name: "Tavuk but",
    aliases: ["chicken thigh", "tavuk baget", "derisiz tavuk but"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 179, protein: 24.76, carbs: 0, fat: 8.15 },
    source: { kind: "usda-fdc", reference: "FDC #172388", description: "Chicken, broilers or fryers, thigh, meat only, cooked, roasted", url: "https://fdc.nal.usda.gov/food-details/172388/nutrients" },
    adet: { grams: 116, label: "1 but (derisiz)", basis: "USDA FDC #172388 ölçüsü: 1 thigh without skin = 116 g" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "dana-kiyma",
    name: "Dana kıyma",
    aliases: ["kiyma", "ground beef", "dana kiyma pismis"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 256, protein: 27.73, carbs: 0, fat: 15.3 },
    source: { kind: "usda-fdc", reference: "FDC #174034", description: "Beef, ground, 85% lean meat / 15% fat, crumbles, cooked, pan-browned", url: "https://fdc.nal.usda.gov/food-details/174034/nutrients" },
    porsiyon: { grams: 100, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: 100 g pişmiş kıyma" },
  },
  {
    id: "dana-bonfile",
    name: "Dana bonfile",
    aliases: ["bonfile", "beef tenderloin", "tenderloin steak"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 196, protein: 30.5, carbs: 0, fat: 8.25 },
    source: { kind: "usda-fdc", reference: "FDC #2705841", description: "Beef, steak, tenderloin", url: "https://fdc.nal.usda.gov/food-details/2705841/nutrients" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "kuzu-eti",
    name: "Kuzu eti",
    aliases: ["lamb", "kuzu but", "lamb leg"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 258, protein: 25.55, carbs: 0, fat: 16.48 },
    source: { kind: "usda-fdc", reference: "FDC #174312", description: "Lamb, leg, whole (shank and sirloin), separable lean and fat, trimmed to 1/4\" fat, choice, cooked, roasted", url: "https://fdc.nal.usda.gov/food-details/174312/nutrients" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "karides",
    name: "Karides",
    aliases: ["shrimp", "prawns"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 99, protein: 23.98, carbs: 0.2, fat: 0.28 },
    source: { kind: "usda-fdc", reference: "FDC #175180", description: "Crustaceans, shrimp, cooked", url: "https://fdc.nal.usda.gov/food-details/175180/nutrients" },
    porsiyon: { grams: 100, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: 100 g" },
  },
  {
    id: "uskumru",
    name: "Uskumru",
    aliases: ["mackerel", "atlantic mackerel"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 262, protein: 23.85, carbs: 0, fat: 17.81 },
    source: { kind: "usda-fdc", reference: "FDC #175120", description: "Fish, mackerel, Atlantic, cooked, dry heat", url: "https://fdc.nal.usda.gov/food-details/175120/nutrients" },
    adet: { grams: 88, label: "1 fileto", basis: "USDA FDC #175120 ölçüsü: 1 fillet = 88 g" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "alabalik",
    name: "Alabalık",
    aliases: ["trout", "rainbow trout"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 168, protein: 23.8, carbs: 0, fat: 7.38 },
    source: { kind: "usda-fdc", reference: "FDC #173718", description: "Fish, trout, rainbow, farmed, cooked, dry heat", url: "https://fdc.nal.usda.gov/food-details/173718/nutrients" },
    adet: { grams: 71, label: "1 fileto", basis: "USDA FDC #173718 ölçüsü: 1 fillet = 71 g" },
    porsiyon: { grams: 150, label: "1 porsiyon (pişmiş)", basis: "YAK tanımı: pişmiş et/balık porsiyonu 150 g" },
  },
  {
    id: "whey-protein",
    name: "Whey protein tozu",
    aliases: ["whey", "whey protein", "protein tozu", "protein powder"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 352, protein: 78.13, carbs: 6.25, fat: 1.56 },
    source: { kind: "usda-fdc", reference: "FDC #173180", description: "Beverages, Protein powder whey based", url: "https://fdc.nal.usda.gov/food-details/173180/nutrients" },
    porsiyon: { grams: 32, label: "1 ölçek", basis: "USDA FDC #173180 ölçüsü: 0.33 cup = 32 g" },
  },
  {
    id: "beyaz-peynir",
    name: "Beyaz peynir",
    aliases: ["tam yagli beyaz peynir", "white cheese"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 213, protein: 12, carbs: 3, fat: 17 },
    source: { kind: "manufacturer-label", reference: "Sütaş ürün etiketi", description: "Sütaş Beyaz Peynir (100 g)", url: "https://www.sutas.com/sutas-white-cheese-250-g" },
    porsiyon: { grams: 30, label: "1 kibrit kutusu dilim", basis: "YAK tanımı: 1 kibrit kutusu büyüklüğünde peynir = 30 g" },
  },
  {
    id: "kasar-peyniri",
    name: "Kaşar peyniri",
    aliases: ["kasar", "taze kasar"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 343, protein: 25, carbs: 1, fat: 26.5 },
    source: { kind: "manufacturer-label", reference: "Pınar ürün etiketi", description: "Pınar Taze Kaşar (100 g)", url: "https://www.pinar.com.tr/urunler/detay-sut/Pinar-Taze-Kasar/3699/138/0" },
    porsiyon: { grams: 30, label: "1 kibrit kutusu dilim", basis: "YAK tanımı: 30 g" },
  },
  {
    id: "bulgur",
    name: "Bulgur (haşlanmış)",
    aliases: ["bulgur", "haslanmis bulgur", "bulgur cooked"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 83, protein: 3.08, carbs: 18.58, fat: 0.24 },
    source: { kind: "usda-fdc", reference: "FDC #170287", description: "Bulgur, cooked", url: "https://fdc.nal.usda.gov/food-details/170287/nutrients" },
    porsiyon: { grams: 182, label: "1 su bardağı (pişmiş)", basis: "USDA FDC #170287 ölçüsü: 1 cup = 182 g" },
  },
  {
    id: "makarna",
    name: "Makarna (haşlanmış)",
    aliases: ["makarna", "spaghetti", "spagetti", "haslanmis makarna"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 158, protein: 5.8, carbs: 30.86, fat: 0.93 },
    source: { kind: "usda-fdc", reference: "FDC #169737", description: "Pasta, cooked, enriched, without added salt", url: "https://fdc.nal.usda.gov/food-details/169737/nutrients" },
    porsiyon: { grams: 124, label: "1 su bardağı (pişmiş)", basis: "USDA FDC #169737 ölçüsü: 1 cup spaghetti = 124 g" },
  },
  {
    id: "beyaz-ekmek",
    name: "Beyaz ekmek",
    aliases: ["ekmek", "white bread", "francala"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 266, protein: 8.85, carbs: 49.42, fat: 3.33 },
    source: { kind: "usda-fdc", reference: "FDC #174924", description: "Bread, white, commercially prepared (includes soft bread crumbs)", url: "https://fdc.nal.usda.gov/food-details/174924/nutrients" },
    porsiyon: { grams: 25, label: "1 ince dilim", basis: "YAK tanımı: 1 ince dilim ekmek = 25 g" },
  },
  {
    id: "tam-bugday-ekmegi",
    name: "Tam buğday ekmeği",
    aliases: ["tam bugday ekmek", "whole wheat bread", "tam bugday"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 252, protein: 12.45, carbs: 42.71, fat: 3.5 },
    source: { kind: "usda-fdc", reference: "FDC #172688", description: "Bread, whole-wheat, commercially prepared", url: "https://fdc.nal.usda.gov/food-details/172688/nutrients" },
    porsiyon: { grams: 25, label: "1 ince dilim", basis: "YAK tanımı: 1 ince dilim ekmek = 25 g" },
  },
  {
    id: "lavas",
    name: "Lavaş",
    aliases: ["lavash"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 286, protein: 11.6, carbs: 47.4, fat: 6.3 },
    source: { kind: "manufacturer-label", reference: "Untad ürün etiketi", description: "Untad Tortilla Lavaş 30 cm (100 g)", url: "https://www.untad.com/products/tortilla-lavas-30-cm/" },
    porsiyon: { grams: 50, label: "1 porsiyon", basis: "Untad etiketi: 1 porsiyon = 50 g" },
  },
  { id: "simit", name: "Simit", aliases: ["gevrek"], state: "as-sold", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: USDA'da karşılığı yok, üreticinin yayımladığı bir etiket bulunamadı." },
  {
    id: "pirinc-patlagi",
    name: "Pirinç patlağı",
    aliases: ["rice cake", "rice cakes", "pirinc patlagi"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 387, protein: 8.2, carbs: 81.5, fat: 2.8 },
    source: { kind: "usda-fdc", reference: "FDC #170250", description: "Snacks, rice cakes, brown rice, plain, unsalted", url: "https://fdc.nal.usda.gov/food-details/170250/nutrients" },
    adet: { grams: 9, label: "1 adet", basis: "USDA FDC #170250 ölçüsü: 1 cake = 9 g" },
  },
  {
    id: "esmer-pirinc",
    name: "Esmer pirinç",
    aliases: ["brown rice", "esmer pirinc pilavi"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 123, protein: 2.74, carbs: 25.58, fat: 0.97 },
    source: { kind: "usda-fdc", reference: "FDC #169704", description: "Rice, brown, long-grain, cooked", url: "https://fdc.nal.usda.gov/food-details/169704/nutrients" },
    porsiyon: { grams: 202, label: "1 su bardağı (pişmiş)", basis: "USDA FDC #169704 ölçüsü: 1 cup = 202 g" },
  },
  {
    id: "patates",
    name: "Patates (haşlanmış)",
    aliases: ["patates", "haslanmis patates", "boiled potato", "potato"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 86, protein: 1.71, carbs: 20.01, fat: 0.1 },
    source: { kind: "usda-fdc", reference: "FDC #170440", description: "Potatoes, boiled, cooked without skin, flesh, without salt", url: "https://fdc.nal.usda.gov/food-details/170440/nutrients" },
    adet: { grams: 167, label: "1 orta boy patates", basis: "USDA FDC #170440 ölçüsü: 1 medium = 167 g" },
  },
  {
    id: "kinoa",
    name: "Kinoa (haşlanmış)",
    aliases: ["kinoa", "quinoa"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 120, protein: 4.4, carbs: 21.3, fat: 1.92 },
    source: { kind: "usda-fdc", reference: "FDC #168917", description: "Quinoa, cooked", url: "https://fdc.nal.usda.gov/food-details/168917/nutrients" },
    porsiyon: { grams: 185, label: "1 su bardağı (pişmiş)", basis: "USDA FDC #168917 ölçüsü: 1 cup = 185 g" },
  },
  {
    id: "nohut",
    name: "Nohut (haşlanmış)",
    aliases: ["nohut", "chickpeas", "haslanmis nohut"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 164, protein: 8.86, carbs: 27.42, fat: 2.59 },
    source: { kind: "usda-fdc", reference: "FDC #173757", description: "Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt", url: "https://fdc.nal.usda.gov/food-details/173757/nutrients" },
    porsiyon: { grams: 164, label: "1 su bardağı (pişmiş)", basis: "USDA FDC #173757 ölçüsü: 1 cup = 164 g" },
  },
  {
    id: "beyaz-fasulye",
    name: "Beyaz fasulye (haşlanmış)",
    aliases: ["beyaz fasulye", "white beans", "haslanmis fasulye"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 139, protein: 9.73, carbs: 25.09, fat: 0.35 },
    source: { kind: "usda-fdc", reference: "FDC #175203", description: "Beans, white, mature seeds, cooked, boiled, without salt", url: "https://fdc.nal.usda.gov/food-details/175203/nutrients" },
    porsiyon: { grams: 179, label: "1 su bardağı (pişmiş)", basis: "USDA FDC #175203 ölçüsü: 1 cup = 179 g" },
  },
  {
    id: "cilek",
    name: "Çilek",
    aliases: ["strawberry", "strawberries"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 32, protein: 0.67, carbs: 7.68, fat: 0.3 },
    source: { kind: "usda-fdc", reference: "FDC #167762", description: "Strawberries, raw", url: "https://fdc.nal.usda.gov/food-details/167762/nutrients" },
    adet: { grams: 12, label: "1 orta boy çilek", basis: "USDA FDC #167762 ölçüsü: 1 medium = 12 g" },
    porsiyon: { grams: 152, label: "1 kase", basis: "USDA FDC #167762 ölçüsü: 1 cup, halves = 152 g" },
  },
  {
    id: "kivi",
    name: "Kivi",
    aliases: ["kiwi", "kiwifruit"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 61, protein: 1.14, carbs: 14.66, fat: 0.52 },
    source: { kind: "usda-fdc", reference: "FDC #168153", description: "Kiwifruit, green, raw", url: "https://fdc.nal.usda.gov/food-details/168153/nutrients" },
    adet: { grams: 69, label: "1 kivi", basis: "USDA FDC #168153 ölçüsü: 1 fruit (2\" dia) = 69 g" },
  },
  {
    id: "uzum",
    name: "Üzüm",
    aliases: ["grapes", "grape"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 69, protein: 0.72, carbs: 18.1, fat: 0.16 },
    source: { kind: "usda-fdc", reference: "FDC #174683", description: "Grapes, red or green (European type, such as Thompson seedless), raw", url: "https://fdc.nal.usda.gov/food-details/174683/nutrients" },
    porsiyon: { grams: 151, label: "1 kase", basis: "USDA FDC #174683 ölçüsü: 1 cup = 151 g" },
  },
  {
    id: "karpuz",
    name: "Karpuz",
    aliases: ["watermelon"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 30, protein: 0.61, carbs: 7.55, fat: 0.15 },
    source: { kind: "usda-fdc", reference: "FDC #167765", description: "Watermelon, raw", url: "https://fdc.nal.usda.gov/food-details/167765/nutrients" },
    porsiyon: { grams: 286, label: "1 dilim", basis: "USDA FDC #167765 ölçüsü: 1 wedge (approx 1/16 of melon) = 286 g" },
  },
  {
    id: "armut",
    name: "Armut",
    aliases: ["pear", "pears"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 57, protein: 0.36, carbs: 15.23, fat: 0.14 },
    source: { kind: "usda-fdc", reference: "FDC #169118", description: "Pears, raw", url: "https://fdc.nal.usda.gov/food-details/169118/nutrients" },
    adet: { grams: 178, label: "1 orta boy armut", basis: "USDA FDC #169118 ölçüsü: 1 medium = 178 g" },
  },
  {
    id: "hurma",
    name: "Hurma (kuru)",
    aliases: ["hurma", "dates", "kuru hurma"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 282, protein: 2.45, carbs: 75.03, fat: 0.39 },
    source: { kind: "usda-fdc", reference: "FDC #171726", description: "Dates, deglet noor", url: "https://fdc.nal.usda.gov/food-details/171726/nutrients" },
    porsiyon: { grams: 30, label: "1 porsiyon (3-4 hurma)", basis: "YAK tanımı: 30 g" },
  },
  {
    id: "kuru-kayisi",
    name: "Kuru kayısı",
    aliases: ["dried apricot", "dried apricots", "gun kurusu kayisi"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 241, protein: 3.39, carbs: 62.64, fat: 0.51 },
    source: { kind: "usda-fdc", reference: "FDC #173941", description: "Apricots, dried, sulfured, uncooked", url: "https://fdc.nal.usda.gov/food-details/173941/nutrients" },
    porsiyon: { grams: 30, label: "1 porsiyon (~4 kayısı)", basis: "YAK tanımı: 30 g" },
  },
  {
    id: "mandalina",
    name: "Mandalina",
    aliases: ["tangerine", "mandarin"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 53, protein: 0.81, carbs: 13.34, fat: 0.31 },
    source: { kind: "usda-fdc", reference: "FDC #169105", description: "Tangerines, (mandarin oranges), raw", url: "https://fdc.nal.usda.gov/food-details/169105/nutrients" },
    adet: { grams: 88, label: "1 orta boy mandalina", basis: "USDA FDC #169105 ölçüsü: 1 medium = 88 g" },
  },
  {
    id: "ananas",
    name: "Ananas",
    aliases: ["pineapple"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 50, protein: 0.54, carbs: 13.12, fat: 0.12 },
    source: { kind: "usda-fdc", reference: "FDC #169124", description: "Pineapple, raw, all varieties", url: "https://fdc.nal.usda.gov/food-details/169124/nutrients" },
    porsiyon: { grams: 165, label: "1 kase (küp)", basis: "USDA FDC #169124 ölçüsü: 1 cup, chunks = 165 g" },
  },
  {
    id: "kiraz",
    name: "Kiraz",
    aliases: ["cherries", "cherry"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 63, protein: 1.06, carbs: 16.01, fat: 0.2 },
    source: { kind: "usda-fdc", reference: "FDC #171719", description: "Cherries, sweet, raw", url: "https://fdc.nal.usda.gov/food-details/171719/nutrients" },
    porsiyon: { grams: 154, label: "1 kase", basis: "USDA FDC #171719 ölçüsü: 1 cup, without pits = 154 g" },
  },
  {
    id: "seftali",
    name: "Şeftali",
    aliases: ["peach", "peaches"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 39, protein: 0.91, carbs: 9.54, fat: 0.25 },
    source: { kind: "usda-fdc", reference: "FDC #169928", description: "Peaches, yellow, raw", url: "https://fdc.nal.usda.gov/food-details/169928/nutrients" },
    adet: { grams: 150, label: "1 orta boy şeftali", basis: "USDA FDC #169928 ölçüsü: 1 medium = 150 g" },
  },
  {
    id: "brokoli",
    name: "Brokoli (haşlanmış)",
    aliases: ["brokoli", "broccoli"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 35, protein: 2.38, carbs: 7.18, fat: 0.41 },
    source: { kind: "usda-fdc", reference: "FDC #169967", description: "Broccoli, cooked, boiled, drained, without salt", url: "https://fdc.nal.usda.gov/food-details/169967/nutrients" },
    porsiyon: { grams: 156, label: "1 kase", basis: "USDA FDC #169967 ölçüsü: 1 cup, chopped = 2 × 78 g" },
  },
  {
    id: "ispanak",
    name: "Ispanak (haşlanmış)",
    aliases: ["ispanak", "spinach"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 23, protein: 2.97, carbs: 3.75, fat: 0.26 },
    source: { kind: "usda-fdc", reference: "FDC #168463", description: "Spinach, cooked, boiled, drained, without salt", url: "https://fdc.nal.usda.gov/food-details/168463/nutrients" },
    porsiyon: { grams: 180, label: "1 kase", basis: "USDA FDC #168463 ölçüsü: 1 cup = 180 g" },
  },
  {
    id: "havuc",
    name: "Havuç",
    aliases: ["carrot", "carrots"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 41, protein: 0.93, carbs: 9.58, fat: 0.24 },
    source: { kind: "usda-fdc", reference: "FDC #170393", description: "Carrots, raw", url: "https://fdc.nal.usda.gov/food-details/170393/nutrients" },
    adet: { grams: 61, label: "1 orta boy havuç", basis: "USDA FDC #170393 ölçüsü: 1 medium = 61 g" },
  },
  {
    id: "marul",
    name: "Marul",
    aliases: ["lettuce", "romaine"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 17, protein: 1.23, carbs: 3.29, fat: 0.3 },
    source: { kind: "usda-fdc", reference: "FDC #169247", description: "Lettuce, cos or romaine, raw", url: "https://fdc.nal.usda.gov/food-details/169247/nutrients" },
    porsiyon: { grams: 85, label: "1 porsiyon salata", basis: "USDA FDC #169247 ölçüsü: 1 NLEA serving = 85 g" },
  },
  {
    id: "dolmalik-biber",
    name: "Yeşil dolmalık biber",
    aliases: ["dolmalik biber", "green bell pepper", "bell pepper"],
    state: "raw",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 20, protein: 0.86, carbs: 4.64, fat: 0.17 },
    source: { kind: "usda-fdc", reference: "FDC #170427", description: "Peppers, sweet, green, raw", url: "https://fdc.nal.usda.gov/food-details/170427/nutrients" },
    adet: { grams: 119, label: "1 orta boy biber", basis: "USDA FDC #170427 ölçüsü: 1 medium = 119 g" },
  },
  {
    id: "mantar",
    name: "Mantar (haşlanmış)",
    aliases: ["mantar", "mushroom", "mushrooms"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 28, protein: 2.17, carbs: 5.29, fat: 0.47 },
    source: { kind: "usda-fdc", reference: "FDC #169252", description: "Mushrooms, white, cooked, boiled, drained, without salt", url: "https://fdc.nal.usda.gov/food-details/169252/nutrients" },
    porsiyon: { grams: 156, label: "1 kase", basis: "USDA FDC #169252 ölçüsü: 1 cup pieces = 156 g" },
  },
  {
    id: "fistik-ezmesi",
    name: "Fıstık ezmesi",
    aliases: ["peanut butter", "fistik ezmesi sade"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 598, protein: 22.21, carbs: 22.31, fat: 51.36 },
    source: { kind: "usda-fdc", reference: "FDC #172470", description: "Peanut butter, smooth style, without salt", url: "https://fdc.nal.usda.gov/food-details/172470/nutrients" },
    porsiyon: { grams: 32, label: "2 yemek kaşığı", basis: "USDA FDC #172470 ölçüsü: 2 tbsp = 32 g" },
  },
  {
    id: "yer-fistigi",
    name: "Yer fıstığı",
    aliases: ["peanut", "peanuts", "kavrulmus yer fistigi"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 587, protein: 24.35, carbs: 21.26, fat: 49.66 },
    source: { kind: "usda-fdc", reference: "FDC #173806", description: "Peanuts, all types, dry-roasted, without salt", url: "https://fdc.nal.usda.gov/food-details/173806/nutrients" },
    porsiyon: { grams: 28.35, label: "1 avuç", basis: "USDA FDC #173806 ölçüsü: 1 oz = 28.35 g" },
  },
  {
    id: "findik",
    name: "Fındık",
    aliases: ["hazelnut", "hazelnuts", "kavrulmus findik"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 646, protein: 15.03, carbs: 17.6, fat: 62.4 },
    source: { kind: "usda-fdc", reference: "FDC #170583", description: "Nuts, hazelnuts or filberts, dry roasted, without salt added", url: "https://fdc.nal.usda.gov/food-details/170583/nutrients" },
    porsiyon: { grams: 30, label: "1 avuç", basis: "YAK tanımı: 30 g" },
  },
  {
    id: "zeytinyagi",
    name: "Zeytinyağı",
    aliases: ["olive oil", "sizma zeytinyagi"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 884, protein: 0, carbs: 0, fat: 100 },
    source: { kind: "usda-fdc", reference: "FDC #171413", description: "Oil, olive, salad or cooking", url: "https://fdc.nal.usda.gov/food-details/171413/nutrients" },
    density: { gramsPerMl: 0.913, basis: "USDA FDC #171413 ölçüsü: 1 yemek kaşığı (14,79 ml) zeytinyağı = 13,5 g" },
    porsiyon: { grams: 13.5, label: "1 yemek kaşığı", basis: "USDA FDC #171413 ölçüsü: 1 tablespoon = 13.5 g" },
  },
  {
    id: "tereyagi",
    name: "Tereyağı",
    aliases: ["butter"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 717, protein: 0.85, carbs: 0.06, fat: 81.11 },
    source: { kind: "usda-fdc", reference: "FDC #173430", description: "Butter, without salt", url: "https://fdc.nal.usda.gov/food-details/173430/nutrients" },
    porsiyon: { grams: 10, label: "1 tatlı kaşığı", basis: "YAK tanımı: 10 g" },
  },
  { id: "siyah-zeytin", name: "Siyah zeytin", aliases: ["siyah zeytin salamura", "black olives"], state: "as-sold", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: USDA kaydı ABD usulü (kostikle olgunlaştırılmış) konserve zeytin; Türk salamura siyah zeytinle eşleşmiyor." },
  {
    id: "tahin",
    name: "Tahin",
    aliases: ["tahini"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 595, protein: 17, carbs: 21.19, fat: 53.76 },
    source: { kind: "usda-fdc", reference: "FDC #170189", description: "Seeds, sesame butter, tahini, from roasted and toasted kernels (most common type)", url: "https://fdc.nal.usda.gov/food-details/170189/nutrients" },
    porsiyon: { grams: 15, label: "1 yemek kaşığı", basis: "YAK tanımı: 1 yemek kaşığı tahin = 15 g" },
  },
  {
    id: "bal",
    name: "Bal",
    aliases: ["honey", "cicek bali"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 304, protein: 0.3, carbs: 82.4, fat: 0 },
    source: { kind: "usda-fdc", reference: "FDC #169640", description: "Honey", url: "https://fdc.nal.usda.gov/food-details/169640/nutrients" },
    porsiyon: { grams: 21, label: "1 yemek kaşığı", basis: "USDA FDC #169640 ölçüsü: 1 tbsp honey = 21 g" },
  },
  { id: "pekmez", name: "Pekmez", aliases: ["uzum pekmezi", "grape molasses"], state: "as-sold", status: 'unavailable', unavailableReason: "Ticari kullanıma uygun, doğrulanmış bir besin değeri kaynağı bulunamadı: USDA'daki \"Molasses\" şeker kamışı melası, üzüm pekmezi değil; üreticinin yayımladığı bir etiket bulunamadı." },
  {
    id: "chia",
    name: "Chia tohumu",
    aliases: ["chia", "chia seeds"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 486, protein: 16.54, carbs: 42.12, fat: 30.74 },
    source: { kind: "usda-fdc", reference: "FDC #170554", description: "Seeds, chia seeds, dried", url: "https://fdc.nal.usda.gov/food-details/170554/nutrients" },
    porsiyon: { grams: 28.35, label: "1 porsiyon (~2,5 yemek kaşığı)", basis: "USDA FDC #170554 ölçüsü: 1 oz = 28.35 g" },
  },
  {
    id: "keten-tohumu",
    name: "Keten tohumu",
    aliases: ["flaxseed", "flax seeds", "keten"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 534, protein: 18.29, carbs: 28.88, fat: 42.16 },
    source: { kind: "usda-fdc", reference: "FDC #169414", description: "Seeds, flaxseed", url: "https://fdc.nal.usda.gov/food-details/169414/nutrients" },
    porsiyon: { grams: 10.3, label: "1 yemek kaşığı", basis: "USDA FDC #169414 ölçüsü: 1 tbsp, whole = 10.3 g" },
  },
  {
    id: "portakal-suyu",
    name: "Portakal suyu (taze)",
    aliases: ["portakal suyu", "orange juice", "taze portakal suyu"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 45, protein: 0.7, carbs: 10.4, fat: 0.2 },
    source: { kind: "usda-fdc", reference: "FDC #169098", description: "Orange juice, raw", url: "https://fdc.nal.usda.gov/food-details/169098/nutrients" },
    density: { gramsPerMl: 1.048, basis: "USDA FDC #169098 ölçüsü: 1 cup (236,6 ml) = 248 g" },
    porsiyon: { ml: 200, label: "1 su bardağı", basis: "YAK tanımı: 1 su bardağı = 200 ml" },
  },
  {
    id: "izotonik",
    name: "İzotonik sporcu içeceği",
    aliases: ["izotonik icecek", "sports drink", "sporcu icecegi"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 26, protein: 0, carbs: 6.43, fat: 0 },
    source: { kind: "usda-fdc", reference: "FDC #2710771", description: "Sports drink, NFS", url: "https://fdc.nal.usda.gov/food-details/2710771/nutrients" },
    density: { gramsPerMl: 1.048, basis: "USDA FDC #2710771 ölçüsü: 12 fl oz (354,9 ml) sporcu içeceği = 372 g" },
    adet: { ml: 500, label: "1 şişe (500 ml)", basis: "Yaygın şişe hacmi 500 ml" },
  },
  {
    id: "siyah-cay",
    name: "Siyah çay (şekersiz)",
    aliases: ["cay", "siyah cay", "tea", "black tea"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 1, protein: 0, carbs: 0.3, fat: 0 },
    source: { kind: "usda-fdc", reference: "FDC #173227", description: "Beverages, tea, black, brewed, prepared with tap water", url: "https://fdc.nal.usda.gov/food-details/173227/nutrients" },
    density: { gramsPerMl: 1.001, basis: "USDA FDC #173227 ölçüsü: 1 fl oz (29,57 ml) = 29,6 g" },
    porsiyon: { ml: 100, label: "1 çay bardağı", basis: "YAK tanımı: 1 çay bardağı = 100 ml" },
  },
  {
    id: "filtre-kahve",
    name: "Filtre kahve (sade)",
    aliases: ["filtre kahve", "coffee", "black coffee", "americano", "sade filtre kahve"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 1, protein: 0.12, carbs: 0, fat: 0.02 },
    source: { kind: "usda-fdc", reference: "FDC #171890", description: "Beverages, coffee, brewed, prepared with tap water", url: "https://fdc.nal.usda.gov/food-details/171890/nutrients" },
    density: { gramsPerMl: 1.001, basis: "USDA FDC #171890 ölçüsü: 1 fl oz (29,57 ml) = 29,6 g" },
    porsiyon: { ml: 240, label: "1 kupa", basis: "YAK tanımı: 1 kupa = 240 ml" },
  },
  {
    id: "pilav",
    name: "Pilav",
    aliases: ["pilav", "pirinc pilavi", "tereyagli pilav", "rice pilaf"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 137, protein: 3.29, carbs: 24.08, fat: 3.03 },
    source: { kind: "usda-fdc", reference: "FDC #2709077", description: "Rice pilaf", url: "https://fdc.nal.usda.gov/food-details/2709077/nutrients" },
    porsiyon: { grams: 158, label: "1 su bardağı (pişmiş)", basis: "YAK tanımı: 1 su bardağı pişmiş pirinç = 158 g (USDA FDC #168878 ölçüsü)" },
  },
  {
    id: "menemen",
    name: "Menemen",
    aliases: ["menemen", "domatesli yumurta", "scrambled egg with tomatoes"],
    state: "cooked",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 165, protein: 10.29, carbs: 1.47, fat: 13.19 },
    source: { kind: "usda-fdc", reference: "FDC #2707229", description: "Egg omelet or scrambled egg, with tomatoes, fat added", url: "https://fdc.nal.usda.gov/food-details/2707229/nutrients" },
  },
  {
    id: "kofte",
    name: "Köfte",
    aliases: ["kofte", "izgara kofte", "kasap kofte", "uzman kasap kofte", "migros kofte", "dana kofte", "meatball", "meatballs"],
    state: "as-sold",
    status: 'verified',
    nutrition: { basis: "per100g", calories: 272, protein: 13.66, carbs: 5.99, fat: 21.24 },
    source: { kind: "manufacturer-label", reference: "Migros Uzman Kasap ürün etiketi", description: "Migros Uzman Kasap Izgara Köfte (100 g, çiğ ürün)", url: "https://www.migros.com.tr/uzman-kasap-izgara-kofte-320-g-p-17dee09" },
    porsiyon: { grams: 160, label: "1 porsiyon (yarım paket, çiğ)", basis: "YAK tanımı: 320 g Uzman Kasap Izgara Köfte paketinin yarısı = 160 g (çiğ ağırlık)" },
  },
];
